### ISSUE TITLE
Custom Style Example on web

### ISSUE THREAD

**Issue by mudream4869** [minhur/bootstrap-toggle#146]
The example on [Bootstrap Toggle](http://www.bootstraptoggle.com/)

```css
.toggle.ios, .toggle-on.ios, .toggle-off.ios { border-radius: 20px; }
```

Should be

```css
.toggle.ios .toggle-on, .toggle.ios .toggle-off{ border-radius: 20px; }
```
